# Generated by Django 5.0.1 on 2024-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_native_language_userlanguage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlanguage',
            old_name='lenguage_level',
            new_name='language_level',
        ),
        migrations.RenameField(
            model_name='userlanguage',
            old_name='studying_lenguage',
            new_name='studying_language',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
